# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import watchtower_pb2 as watchtower__pb2


class WatchTowerStub(object):
  """Server exported interface
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDriverStatus = channel.unary_unary(
        '/watchtower.WatchTower/GetDriverStatus',
        request_serializer=watchtower__pb2.DriverId.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatus.FromString,
        )
    self.SetDriverStatus = channel.unary_unary(
        '/watchtower.WatchTower/SetDriverStatus',
        request_serializer=watchtower__pb2.DriverStatus.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatus.FromString,
        )
    self.PatchDriverStatus = channel.unary_unary(
        '/watchtower.WatchTower/PatchDriverStatus',
        request_serializer=watchtower__pb2.DriverStatus.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatus.FromString,
        )
    self.ListDriverStatus = channel.unary_unary(
        '/watchtower.WatchTower/ListDriverStatus',
        request_serializer=watchtower__pb2.DriverStatusFilters.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatusList.FromString,
        )
    self.DeleteDriverStatus = channel.unary_unary(
        '/watchtower.WatchTower/DeleteDriverStatus',
        request_serializer=watchtower__pb2.DriverStatusFilters.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatusList.FromString,
        )
    self.ListOfferCandidates = channel.unary_unary(
        '/watchtower.WatchTower/ListOfferCandidates',
        request_serializer=watchtower__pb2.OrderOffer.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatusList.FromString,
        )
    self.ListOfferRoundCandidates = channel.unary_unary(
        '/watchtower.WatchTower/ListOfferRoundCandidates',
        request_serializer=watchtower__pb2.OrderOffer.SerializeToString,
        response_deserializer=watchtower__pb2.DriverStatusList.FromString,
        )
    self.RunOfferRound = channel.unary_unary(
        '/watchtower.WatchTower/RunOfferRound',
        request_serializer=watchtower__pb2.OrderOffer.SerializeToString,
        response_deserializer=watchtower__pb2.OrderOfferRoundResponse.FromString,
        )


class WatchTowerServicer(object):
  """Server exported interface
  """

  def GetDriverStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDriverStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchDriverStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListDriverStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDriverStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListOfferCandidates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListOfferRoundCandidates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunOfferRound(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WatchTowerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDriverStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetDriverStatus,
          request_deserializer=watchtower__pb2.DriverId.FromString,
          response_serializer=watchtower__pb2.DriverStatus.SerializeToString,
      ),
      'SetDriverStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SetDriverStatus,
          request_deserializer=watchtower__pb2.DriverStatus.FromString,
          response_serializer=watchtower__pb2.DriverStatus.SerializeToString,
      ),
      'PatchDriverStatus': grpc.unary_unary_rpc_method_handler(
          servicer.PatchDriverStatus,
          request_deserializer=watchtower__pb2.DriverStatus.FromString,
          response_serializer=watchtower__pb2.DriverStatus.SerializeToString,
      ),
      'ListDriverStatus': grpc.unary_unary_rpc_method_handler(
          servicer.ListDriverStatus,
          request_deserializer=watchtower__pb2.DriverStatusFilters.FromString,
          response_serializer=watchtower__pb2.DriverStatusList.SerializeToString,
      ),
      'DeleteDriverStatus': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDriverStatus,
          request_deserializer=watchtower__pb2.DriverStatusFilters.FromString,
          response_serializer=watchtower__pb2.DriverStatusList.SerializeToString,
      ),
      'ListOfferCandidates': grpc.unary_unary_rpc_method_handler(
          servicer.ListOfferCandidates,
          request_deserializer=watchtower__pb2.OrderOffer.FromString,
          response_serializer=watchtower__pb2.DriverStatusList.SerializeToString,
      ),
      'ListOfferRoundCandidates': grpc.unary_unary_rpc_method_handler(
          servicer.ListOfferRoundCandidates,
          request_deserializer=watchtower__pb2.OrderOffer.FromString,
          response_serializer=watchtower__pb2.DriverStatusList.SerializeToString,
      ),
      'RunOfferRound': grpc.unary_unary_rpc_method_handler(
          servicer.RunOfferRound,
          request_deserializer=watchtower__pb2.OrderOffer.FromString,
          response_serializer=watchtower__pb2.OrderOfferRoundResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'watchtower.WatchTower', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
